import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: {
        "2xl": "1280px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        neutral: {
          50: "hsl(var(--neutral-50))",
          100: "hsl(var(--neutral-100))",
          200: "hsl(var(--neutral-200))",
          300: "hsl(var(--neutral-300))",
          400: "hsl(var(--neutral-400))",
          500: "hsl(var(--neutral-500))",
          600: "hsl(var(--neutral-600))",
          700: "hsl(var(--neutral-700))",
          800: "hsl(var(--neutral-800))",
          900: "hsl(var(--neutral-900))",
          950: "hsl(var(--neutral-950))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--primary-50))",
          100: "hsl(var(--primary-100))",
          200: "hsl(var(--primary-200))",
          300: "hsl(var(--primary-300))",
          400: "hsl(var(--primary-400))",
          500: "hsl(var(--primary-500))",
          600: "hsl(var(--primary-600))",
          700: "hsl(var(--primary-700))",
          800: "hsl(var(--primary-800))",
          900: "hsl(var(--primary-900))",
          950: "hsl(var(--primary-950))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "hsl(var(--secondary-50))",
          100: "hsl(var(--secondary-100))",
          200: "hsl(var(--secondary-200))",
          300: "hsl(var(--secondary-300))",
          400: "hsl(var(--secondary-400))",
          500: "hsl(var(--secondary-500))",
          600: "hsl(var(--secondary-600))",
          700: "hsl(var(--secondary-700))",
          800: "hsl(var(--secondary-800))",
          900: "hsl(var(--secondary-900))",
          950: "hsl(var(--secondary-950))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        red: {
          50: "hsl(var(--red-50))",
          100: "hsl(var(--red-100))",
          200: "hsl(var(--red-200))",
          300: "hsl(var(--red-300))",
          400: "hsl(var(--red-400))",
          500: "hsl(var(--red-500))",
          600: "hsl(var(--red-600))",
          700: "hsl(var(--red-700))",
          800: "hsl(var(--red-800))",
          900: "hsl(var(--red-900))",
          950: "hsl(var(--red-950))",
        },
        yellow: {
          50: "hsl(var(--yellow-50))",
          100: "hsl(var(--yellow-100))",
          200: "hsl(var(--yellow-200))",
          300: "hsl(var(--yellow-300))",
          400: "hsl(var(--yellow-400))",
          500: "hsl(var(--yellow-500))",
          600: "hsl(var(--yellow-600))",
          700: "hsl(var(--yellow-700))",
          800: "hsl(var(--yellow-800))",
          900: "hsl(var(--yellow-900))",
          950: "hsl(var(--yellow-950))",
        },
        green: {
          50: "hsl(var(--green-50))",
          100: "hsl(var(--green-100))",
          200: "hsl(var(--green-200))",
          300: "hsl(var(--green-300))",
          400: "hsl(var(--green-400))",
          500: "hsl(var(--green-500))",
          600: "hsl(var(--green-600))",
          700: "hsl(var(--green-700))",
          800: "hsl(var(--green-800))",
          900: "hsl(var(--green-900))",
          950: "hsl(var(--green-950))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        reader: {
          bg: "hsl(var(--reader-bg))",
          read: "hsl(var(--highlight-read))",
          focus: "hsl(var(--highlight-focus))",
          miss: "hsl(var(--highlight-miss))",
        },
        status: {
          read: "hsl(var(--status-read))",
          partial: "hsl(var(--status-partial))",
          notread: "hsl(var(--status-not-read))",
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        pill: "var(--radius-pill)",
        control: "var(--radius-control)",
        surface: "var(--radius-surface)",
      },
      borderWidth: {
        hairline: "var(--line-1)",
        thick: "var(--line-2)",
        heavy: "var(--line-4)",
      },
      boxShadow: {
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
        3: "var(--shadow-3)",
        e0: "var(--shadow-e0)",
        e1: "var(--shadow-e1)",
        e2: "var(--shadow-e2)",
        e3: "var(--shadow-e3)",
        soft: "var(--shadow-soft-diffusion)",
        strong: "var(--shadow-strong-diffusion)",
        sunken: "var(--shadow-sunken)",
        glow: "var(--shadow-glow-primary)",
        "glow-secondary": "var(--shadow-glow-secondary)",
        brutal: "var(--shadow-neobrutal)",
      },
      spacing: {
        gutter: "var(--content-gutter)",
        topbar: "var(--topbar-height)",
        "bottom-nav": "var(--bottom-nav-height)",
        "space-0": "var(--space-0)",
        "space-1": "var(--space-1)",
        "space-2": "var(--space-2)",
        "space-3": "var(--space-3)",
        "space-4": "var(--space-4)",
        "space-5": "var(--space-5)",
        "space-6": "var(--space-6)",
        "space-8": "var(--space-8)",
        "space-10": "var(--space-10)",
        "space-12": "var(--space-12)",
        "space-16": "var(--space-16)",
      },
      maxWidth: {
        reader: "42rem",
      },
      fontFamily: {
        sans: [
          "var(--font-sans)",
          "-apple-system",
          "BlinkMacSystemFont",
          "Apple SD Gothic Neo",
          "Noto Sans KR",
          "Segoe UI",
          "sans-serif",
        ],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        "ui-xs": ["var(--text-xs)", { lineHeight: "1.33", letterSpacing: "var(--tracking-normal)" }],
        "ui-sm": ["var(--text-sm)", { lineHeight: "1.45", letterSpacing: "var(--tracking-normal)" }],
        "ui-base": ["var(--text-base)", { lineHeight: "var(--line-height-ui)", letterSpacing: "var(--tracking-normal)" }],
        "ui-lg": ["var(--text-lg)", { lineHeight: "1.55", letterSpacing: "var(--tracking-snug)" }],
        "ui-xl": ["var(--text-xl)", { lineHeight: "1.35", letterSpacing: "var(--tracking-snug)" }],
        "ui-2xl": ["var(--text-2xl)", { lineHeight: "1.2", letterSpacing: "var(--tracking-tight)" }],
        reader: [
          "clamp(var(--text-reader-min), 5.2vw, var(--text-reader-max))",
          { lineHeight: "var(--line-height-reader)", letterSpacing: "var(--tracking-normal)" },
        ],
      },
      lineHeight: {
        reader: "var(--line-height-reader)",
        ui: "var(--line-height-ui)",
        tight: "var(--leading-tight)",
        snug: "var(--leading-snug)",
        relaxed: "var(--leading-relaxed)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        base: "var(--duration-base)",
        slow: "var(--duration-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--easing-standard)",
        emphasis: "var(--easing-emphasis)",
        exit: "var(--easing-exit)",
      },
      keyframes: {
        "mic-pulse": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.88" },
          "50%": { transform: "scale(1.03)", opacity: "1" },
        },
      },
      animation: {
        "mic-pulse": "mic-pulse var(--duration-pulse) ease-in-out infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
